version: '3.3'

services:
  db:
    image: postgres
    ports:
      - 5454:5432
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - dev-db-back:/app/backend
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    
volumes:
  dev-db-back:
  dev-db-data: