on: push # cuando se haga un push lo que hace es correr este trabajo y este trabajo se llama deploy
name: deploy
jobs:
  deploy:
    name: deploy to cluster # deplegar en el cluster que vamos a crear
    runs-on: ubuntu-latest # esto es para saber donde va a correr, esto es como una maquina virtual, la que va a correr el codigo
    steps: # pasos que vamos a correr dentro de la maquina virtual, estos pasos son las actions
    - uses: actions/checkout@master # primer paso, usar la actions checkout@master
    - name: build and push to docker # segundo paso, construye la imagen y la sube a docker hub
      uses: docker/build-push-actions@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.pruebaTecnica-Craftech }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
