name: ci
on:
  push:
    branches:
      - 'master'
    paths:
      - 'prueba-3/html/index.html'

jobs:
  docker-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Entrar en rama
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mrhalvarez/craftech
          dockerfile: prueba-3/Dockerfile

      - name: construir el docker compose
        run: docker-compose -f ./prueba-3/docker-compose.yml up -d
